name: build-and-test

on:
  workflow_dispatch

jobs:
  build_and_test:
    runs: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup
      uses: actions/setup-pyhton@v3
      with:
        pyhton-version: 3.11
      - name: install
      run: | 
        python -m pip install --upgrade pip
        pip install pytest
      
      - name: test
      run: |
        pytest -v /tests
